### ISSUE TITLE
Editing text error 

### ISSUE THREAD

**Issue by hoytpr** [carpentries-incubator/capstone-novice-spreadsheet-biblio#12]
In http://swcarpentry.github.io/capstone-novice-spreadsheet-biblio/03-db.html the statement: "Again, we have a data normalization problem: the pair “Vincent, Pascal” and “Bengio, Yoshua” is almost certainly the same as the pair “Bengio, Y.” and “Bengio, S.”. 

Should be:

Again, we have a data normalization problem: the pair “Vincent, Pascal” and “Bengio, Yoshua” is almost certainly the same as the pair “Vincent, P.” and “Bengio, S.”.   @gvwilson

**Comment by Denubis** [comment]
Hi @hoytpr, I'm the new maintainer.

A large (historical) edit was just committed. Is this error still present?

**Comment by hoytpr** [comment]
Yes it is, in episode04.
