### ISSUE TITLE
Issues at instructors.md

### ISSUE THREAD

**Issue by rgaiacs** [carpentries-incubator/capstone-novice-spreadsheet-biblio#2]
From https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/check.py:
- [ ] The document links to 01-one.html, but could not find the expected markdown file /tmp/biblio/01-one.md
- [ ] The document links to 02-two.html, but could not find the expected markdown file /tmp/biblio/02-two.md

**Comment by gvwilson** [comment]
Out of date.
