### ISSUE TITLE
Issues at motivation.md

### ISSUE THREAD

**Issue by rgaiacs** [carpentries-incubator/capstone-novice-spreadsheet-biblio#3]
From https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/check.py:
- [ ] The linked page motivation.html exists, but the link text 'Motivation' does not match the (sub)title of that page, ''.
- [ ] Header section is missing expected row 'subtitle'

**Comment by gvwilson** [comment]
Out of date (but motivation still needs to be written).
